print('회원 정보를 입력하세요.')
userName = input('이름 : ')
userMail = input('메일 : ')
userId = input('아이디 : ')
userPw = input('비밀번호 : ')

print('To. ' + userMail)
print('- 아이디 및 비밀번호 확인')
print(userName + ' 고객님 안녕하세요.')
print('고객님의 아이디와 비밀번호는 아래과 같습니다.')
print('아이디 : ' + userId)
print('비밀번호 : ' + userPw)


# print('회원 정보를 입력하세요.')
# name = input('이름 : ')
# mail = input('메일 : ')
# id = input('아이디 : ')
# pw = input('비밀번호 : ')
# print('----------------')
# print('To.', mail)
# print('*아이디 및 비밀번호 확인')
# print(name,'고객님, 안녕하세요. \n고객님의 아이디와 비밀번호는 아래와 같습니다.')
# print('아이디 : ',id)
# print('비밀번호 : ',pw)